name: "count file of directory"
description: 'get the file counts of directory and generated the matrix automatically, like this way: ["1", "2", "3"]'

inputs:
  path:
    description: "The directory which is the files you want to count"
    required: true

outputs:
  count_for_matrix:
    value: ${{ steps.test.outputs.str }}

runs:
  using: "composite"
  steps:
    - name: Count files number
      id: test
      shell: bash
      run: |
        cd ${{ inputs.path }}
        count=$(ls -l | grep "^-" | wc -l)

        str="["
        for ((i=1; i<=$count; i++))
        do
          if [[ $i -eq 1 ]] ;
            then
              str=$str'"'$i'"';
            else
              str=$str',"'$i'"';
          fi
        done
        str=$str"]"

        echo "str=$str" >> $GITHUB_OUTPUT
