name: "yarn cache"
description: 'cache node_modules by yarn'

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: |
        echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        echo "version=$(yarn -v)" >> $GITHUB_OUTPUT
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install