name: "check service healthy"
description: 'check input's services is healthy'

inputs:
  services_name:
    description: "the service which u want to wait for"
    required: true
    is-array: true

runs:
  using: "composite"
  steps:
    - name: Check services is healthy
      shell: bash
      run: |
        result=$(docker inspect -f {{.State.Health.Status}} $(docker-compose ps -q ${{ inputs.services_name }}) | grep "unhealthy")
        if [[ "$result" != "" ]];then exit 1; else exit 0; fi