name: "pr branch name"

runs:
  using: "composite"
  steps:
    - name: install jq
      shell: bash
      run: |
        sudo apt-get install jq
    - name: pr_commit_sha
      shell: bash
      run: echo "PR_BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -r 's,/,-,g' | tr A-Z a-z)" >> $GITHUB_ENV