name: "ssh docker update"
description: 'auto deploy the container'

inputs:
  services_name:
    required: true
    type: string
    is-array: true
  path:
    required: true
    type: string
    description: "where is the docker compose path're"
  host:
    description: "url host"
    required: true
  username:
    description: "username"
    required: true
  key:
    description: "ssh key"
    required: true
  passphrase:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run production deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase }}
        script: |
          cd ${{ inputs.path }}
          echo "${{ inputs.services_name }}" > /tmp/services_tmp_name
          services_name=$(awk BEGIN{RS=EOF}'{gsub(/\n/," ");print}' /tmp/services_tmp_name)

          docker compose pull $services_name
          docker compose up -d
        command_timeout: 30m