name: "ghcr tag handler"
description: 'handle the github action ghcr tag and given the required data'

inputs:
  current_tag:
    description: "current ghcr tag name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get short sha
      uses: wikifactory/wikifactory-actions/short_sha@main
      id: short-sha

    - shell: bash
      id: ghcr_tag_handler
      run: |
# staging
        if [[ "${{ github.event_name }}" == "pull_request" ]];then
          echo "dst_tag_long=master.${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV
          echo "dst_tag_short=master" >> $GITHUB_ENV

          if [[ ${{ inputs.current_tag }} ]]; then
            echo "current_tag=${{ inputs.current_tag }}" >> $GITHUB_ENV
            echo "src=${{ inputs.current_tag }}" >> $GITHUB_ENV
          fi

          echo "is_staging=true" >> $GITHUB_ENV
          echo "is_production=false" >> $GITHUB_ENV
        fi

# production
        if [[ "${{ github.event_name }}" == "release" ]];then
          echo "dst_tag_short=production.${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "dst_tag_long=production" >> $GITHUB_ENV
          echo "is_staging=false" >> $GITHUB_ENV
          echo "is_production=true" >> $GITHUB_ENV

          if [[ ${{ inputs.current_tag }} ]]; then
            echo "current_tag=master.${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV;
          fi

          if [[ "${{ env.TAG_EXISTED }}" == 'true' ]];then
            echo "src_tag=master.${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV;
          else
            echo "src_tag=master" >> $GITHUB_ENV;
          fi
        fi