name: "ghcr tag handler"
description: 'handle the github action ghcr tag and given the required data'

inputs:
  token:
    required: true
  org:
    required: true
  package:
    required: true
  current_tag:
    description: "current ghcr tag name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get short sha
      uses: wikifactory/wikifactory-actions/short_sha@main
      id: short-sha

    - name: Check ghcr tag existed
      uses: wikifactory/wikifactory-actions/check_ghcr_tag_existed@main
      with:
        user: ${{ github.actor }}
        token: ${{ inputs.token }}
        org: ${{ inputs.org }}
        package: ${{ inputs.package }}
        tag: ${{ inputs.current_tag }}

    - shell: bash
      id: ghcr_tag_handler
      run: |
# staging
        if [[ "${{ github.event_name }}" == "pull_request" ]];then
          echo "dst_tag_long=master.${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV
          echo "dst_tag_short=master" >> $GITHUB_ENV

          if [[ ${{ inputs.current_tag }} ]]; then
            echo "current_tag=${{ inputs.current_tag }}" >> $GITHUB_ENV
            echo "src=${{ inputs.current_tag }}" >> $GITHUB_ENV
          fi
        fi

# production
        if [[ "${{ github.event_name }}" == "push" ]];then
          echo "dst_tag_short=production.release-test" >> $GITHUB_ENV
          echo "dst_tag_long=production" >> $GITHUB_ENV

          if [[ ${{ inputs.current_tag }} ]]; then
            echo "current_tag=master.${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV;
          fi

          if [[ "${{ env.TAG_EXISTED }}" == 'true' ]];then
            echo "src_tag=master.${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV;
          else
            echo "src_tag=master" >> $GITHUB_ENV;
          fi
        fi