name: "github short sha"

outputs:
  sha:
    value: ${{ steps.short-sha.outputs.sha }}

runs:
  using: "composite"
  steps:
    - name: Check files if changed
      id: short-sha
      shell: bash
      run: |
        sha=${{ github.sha }}
        echo "sha=${sha:0:7}" >> $GITHUB_OUTPUT
